export const KNOWN_ERROR_KEYS: Readonly<Record<string, string>> = {
  ollama_connection_lost: "errors.ollamaConnectionLost",
  model_not_found: "errors.modelNotFound",
  rate_limit: "errors.rateLimited",
  auth_failed: "errors.authFailed",
  model_catalog_unavailable: "errors.modelCatalogUnavailable",
  moonshot_membership_unverified: "errors.moonshotMembershipUnverified",
  xai_subscription_or_credits_required: "errors.xaiSubscriptionOrCreditsRequired",
  provider_access_unavailable: "errors.providerAccessUnavailable",
  provider_age_confirmation_required: "errors.providerAgeConfirmationRequired",
  provider_quota_exhausted: "errors.providerQuotaExhausted",
  stream_interrupted: "errors.streamInterrupted",
  reasoning_continuity_invalid: "errors.reasoningContinuityInvalid",
  reasoning_configuration_invalid: "errors.reasoningConfigurationInvalid",
  provider_connection_failed: "errors.providerConnectionFailed",
  provider_temporarily_unavailable: "errors.providerTemporarilyUnavailable",
  provider_request_rejected: "errors.providerRequestRejected",
  provider_empty_response: "errors.providerEmptyResponse",
  provider_output_limit: "errors.providerOutputLimit",
  provider_content_filtered: "errors.providerContentFiltered",
  service_tier_unavailable: "errors.serviceTierUnavailable",
  provider_payload_too_large: "errors.providerPayloadTooLarge",
  provider_configuration_invalid: "errors.providerConfigurationInvalid",
  oauth_reauthentication_required: "errors.oauthReauthenticationRequired",
  ollama_server_error: "errors.ollamaServerError",
  connection_lost: "errors.connectionLost",
  timeout: "errors.timeout",
  provider_overloaded: "errors.providerOverloaded",
  provider_error: "errors.providerError",
  max_turns: "errors.maxTurns",
  circuit_breaker: "errors.circuitBreaker",
  tool_error: "errors.toolError",
  stream_error: "errors.streamError",
  compression_unavailable: "errors.compressionUnavailable",
  compression_profiles_unavailable: "errors.compressionProfilesUnavailable",
  compression_disabled_under_64k: "errors.compressionDisabledUnder64",
  compression_automatic_suspended: "errors.compressionAutomaticSuspended",
  compression_failed: "errors.compressionFailed",
  extensions_registry_version_unsupported: "extensions.errors.codes.extensions_registry_version_unsupported",
  extensions_registry_unavailable: "extensions.errors.codes.extensions_registry_unavailable",
  extensions_registry_migration_failed: "extensions.errors.codes.extensions_registry_migration_failed",
  extensions_state_unavailable: "extensions.errors.codes.extensions_state_unavailable",
};

export function isKnownAgentErrorCode(code: string): boolean {
  return Object.prototype.hasOwnProperty.call(KNOWN_ERROR_KEYS, code);
}
