// @generated from Rust by `npm run contracts:generate:installer`.
// Do not edit this file manually.

export type InstallerPhase = "ready" | "checking" | "downloading" | "verifying" | "installing" | "finishing" | "cancelling" | "cancelled" | "failed" | "completed";

export type ProgressMode = "determinate" | "indeterminate";

export type InstallerOutcome = "installed" | "reinstalled";

export type InstallerSnapshot = { version: string, destination: string, installedVersion: string | null, beaverRunning: boolean, phase: InstallerPhase, stepIndex: number, stepCount: number, progressMode: ProgressMode, percent: number | null, canCancel: boolean, outcome: InstallerOutcome | null, errorKey: string | null, };

export type InstallerEvent = { sequence: number, snapshot: InstallerSnapshot, completedStepDurationsMs: number[], logKey: string | null, };
