use super::{
    browser_events::{BrowserSessionEvent, BrowserTabEvent, PopupRequestEvent, EVENT_VERSION},
    local_site_types::{
        LocalSite, LocalSiteProtocol, LocalSiteScanResult, MAX_LOCAL_RESULTS, MAX_LOCAL_TITLE_CHARS,
    },
    session_types::{
        BrowserSessionState, BrowserTabCreation, BrowserTabState, MAX_BROWSER_TABS, MAX_TITLE_CHARS,
    },
    surface_bounds::MAX_DIMENSION,
    url_policy::MAX_BROWSER_URL_LENGTH,
};
use ts_rs::TS;

fn bindings() -> String {
    let config = ts_rs::Config::default();
    let declarations = [
        BrowserTabState::decl(&config),
        BrowserSessionState::decl(&config),
        BrowserTabCreation::decl(&config),
        LocalSiteProtocol::decl(&config),
        LocalSite::decl(&config),
        LocalSiteScanResult::decl(&config),
        BrowserTabEvent::decl(&config),
        PopupRequestEvent::decl(&config),
        BrowserSessionEvent::decl(&config),
    ]
    .join("\nexport ");
    format!(
        "// @generated by Rust browser_contract_tests. Do not edit.\n\nexport {declarations}\nexport const BROWSER_EVENT_VERSION = {EVENT_VERSION};\nexport const MAX_BROWSER_TABS = {MAX_BROWSER_TABS};\nexport const MAX_BROWSER_TITLE_CHARS = {MAX_TITLE_CHARS};\nexport const MAX_BROWSER_URL_LENGTH = {MAX_BROWSER_URL_LENGTH};\nexport const MAX_BROWSER_SURFACE_EDGE = {MAX_DIMENSION};\nexport const MAX_LOCAL_SITES = {MAX_LOCAL_RESULTS};\nexport const MAX_LOCAL_TITLE_CHARS = {MAX_LOCAL_TITLE_CHARS};\n"
    )
}

fn path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../src/components/internal-browser/browser-contract.generated.ts")
}

#[test]
fn checked_in_browser_contract_matches_rust() {
    assert_eq!(
        std::fs::read_to_string(path())
            .unwrap()
            .replace("\r\n", "\n"),
        bindings()
    );
}

#[test]
#[ignore = "explicit contract generation"]
fn export_browser_contract() {
    std::fs::write(path(), bindings()).unwrap();
}
