use super::{
    favicon_events::{BrowserFaviconIcon, BrowserFaviconSnapshot, EVENT_VERSION, FAVICON_EVENT},
    favicon_policy::{MAX_FAVICONS, MAX_PNG_BYTES},
};
use ts_rs::TS;

fn bindings() -> String {
    let config = ts_rs::Config::default();
    format!("// @generated by Rust favicon_contract_tests::export_favicon_contract. Do not edit.\n\nexport {}\nexport {}\nexport const FAVICON_EVENT = {:?};\nexport const FAVICON_EVENT_VERSION = {};\nexport const MAX_FAVICONS = {};\nexport const MAX_FAVICON_PNG_BYTES = {};\n",
        BrowserFaviconIcon::decl(&config), BrowserFaviconSnapshot::decl(&config),
        FAVICON_EVENT, EVENT_VERSION, MAX_FAVICONS, MAX_PNG_BYTES)
}

#[test]
fn checked_in_favicon_contract_matches_rust() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../src/components/internal-browser/browser-favicon-contract.ts");
    assert_eq!(
        std::fs::read_to_string(path).unwrap().replace("\r\n", "\n"),
        bindings()
    );
}

#[test]
#[ignore = "explicit contract generation"]
fn export_favicon_contract() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../src/components/internal-browser/browser-favicon-contract.ts");
    std::fs::write(path, bindings()).unwrap();
}

#[test]
fn invalid_snapshot_request_is_rejected() {
    assert!(super::favicon_events::read_snapshot("../invalid").is_err());
}

#[test]
fn snapshots_isolate_conversations_and_remove_closed_icons() {
    use super::{
        browser_view_key::BrowserViewKey, favicon_events::snapshot, favicon_state::FaviconState,
    };
    let mut state = FaviconState::default();
    let a = BrowserViewKey {
        session_id: "a".into(),
        tab_id: "one".into(),
    };
    let b = BrowserViewKey {
        session_id: "b".into(),
        tab_id: "two".into(),
    };
    state.begin_document(a.clone(), 1);
    state.begin_document(b, 2);
    state.entries[0].png = Some("image-a".into());
    state.entries[1].png = Some("image-b".into());
    let before = snapshot(&state, "a");
    assert_eq!(before.icons.len(), 1);
    assert_eq!(before.icons[0].png_base64, "image-a");
    state.release_view(&a, 1);
    let after = snapshot(&state, "a");
    assert!(after.icons.is_empty());
    assert!(after.revision > before.revision);
}
