use super::contract::{ContinuationUse, ReasoningModeId};
use super::registry::{ModelPolicy, ReplayRequirement};
use super::registry_inventory::{disabled, live};

// Astra remains closed until the Responses route has its exact live proof.
pub(super) const OPENAI: &[ModelPolicy] = &[
    live(
        "gpt-5.6-luna",
        ReasoningModeId::Medium,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
        "openai-api-gpt-5-6-luna-france-2026-08-26",
        "2026-08-26",
    ),
    live(
        "gpt-5.6-luna",
        ReasoningModeId::Medium,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
        "openai-api-gpt-5-6-luna-france-2026-08-26",
        "2026-08-26",
    ),
    disabled(
        "gpt-5.6-terra",
        ReasoningModeId::Medium,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "gpt-5.6-terra",
        ReasoningModeId::Medium,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "gpt-6-astra",
        ReasoningModeId::Low,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "gpt-6-astra",
        ReasoningModeId::Low,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "gpt-6-astra",
        ReasoningModeId::Medium,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "gpt-6-astra",
        ReasoningModeId::Medium,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "gpt-6-astra",
        ReasoningModeId::High,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "gpt-6-astra",
        ReasoningModeId::High,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "gpt-6-astra",
        ReasoningModeId::Xhigh,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "gpt-6-astra",
        ReasoningModeId::Xhigh,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "gpt-6-astra",
        ReasoningModeId::Max,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "gpt-6-astra",
        ReasoningModeId::Max,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
];
