use super::contract::{ContinuationUse, ReasoningModeId};
use super::registry::{ModelPolicy, ReplayRequirement};
use super::registry_inventory::{disabled, live};

// The gateway catalogue is not a replay proof; new models stay closed here.
pub(super) const OPENROUTER: &[ModelPolicy] = &[
    // 2026-09-09: the catalogue now exposes a toggle. Prove auto separately;
    // never reuse a medium envelope or activate its replacement without live evidence.
    disabled(
        "moonshotai/kimi-k2.5",
        ReasoningModeId::Auto,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "moonshotai/kimi-k2.5",
        ReasoningModeId::Auto,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    live(
        "moonshotai/kimi-k2.5",
        ReasoningModeId::Medium,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
        "openrouter-api-moonshotai-kimi-k2-5-france-2026-08-26",
        "2026-08-26",
    ),
    live(
        "moonshotai/kimi-k2.5",
        ReasoningModeId::Medium,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
        "openrouter-api-moonshotai-kimi-k2-5-france-2026-08-26",
        "2026-08-26",
    ),
    disabled(
        "google/gemini-3.8-flash",
        ReasoningModeId::Low,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "google/gemini-3.8-flash",
        ReasoningModeId::Low,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "google/gemini-3.8-flash",
        ReasoningModeId::Medium,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "google/gemini-3.8-flash",
        ReasoningModeId::Medium,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "google/gemini-3.8-flash",
        ReasoningModeId::High,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "google/gemini-3.8-flash",
        ReasoningModeId::High,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "z-ai/glm-5.3-flash",
        ReasoningModeId::Low,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "z-ai/glm-5.3-flash",
        ReasoningModeId::Low,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "z-ai/glm-5.3-flash",
        ReasoningModeId::High,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "z-ai/glm-5.3-flash",
        ReasoningModeId::High,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "z-ai/glm-5.3-flash",
        ReasoningModeId::Max,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "z-ai/glm-5.3-flash",
        ReasoningModeId::Max,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "openai/gpt-6-astra",
        ReasoningModeId::Low,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "openai/gpt-6-astra",
        ReasoningModeId::Low,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "openai/gpt-6-astra",
        ReasoningModeId::Medium,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "openai/gpt-6-astra",
        ReasoningModeId::Medium,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "openai/gpt-6-astra",
        ReasoningModeId::High,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "openai/gpt-6-astra",
        ReasoningModeId::High,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "openai/gpt-6-astra",
        ReasoningModeId::Xhigh,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "openai/gpt-6-astra",
        ReasoningModeId::Xhigh,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "openai/gpt-6-astra",
        ReasoningModeId::Max,
        ContinuationUse::UserContinuation,
        ReplayRequirement::Required,
    ),
    disabled(
        "openai/gpt-6-astra",
        ReasoningModeId::Max,
        ContinuationUse::ToolContinuation,
        ReplayRequirement::Required,
    ),
];
