use super::ollama_modelfile_parameters::rewrite;

#[test]
fn empty_entries_remove_every_top_level_parameter() {
    let input = concat!(
        "# generated by Ollama\n",
        "FROM C:/models/blobs/sha256-base\n",
        "SYSTEM \"\"\"Keep this prompt.\n",
        "PARAMETER num_ctx 777 must remain prompt text.\n",
        "\"\"\"\n",
        "PARAMETER num_ctx 100000\n",
        "PARAMETER temperature 0.8\n",
        "ADAPTER ./adapter.gguf\n",
        "MESSAGE user hello\n",
        "RENDERER gemma4\n",
        "PARSER gemma4\n",
    );

    let output = rewrite(input, &[]).expect("valid generated Modelfile");

    assert_eq!(
        output,
        concat!(
            "# generated by Ollama\n",
            "FROM C:/models/blobs/sha256-base\n",
            "SYSTEM \"\"\"Keep this prompt.\n",
            "PARAMETER num_ctx 777 must remain prompt text.\n",
            "\"\"\"\n",
            "ADAPTER ./adapter.gguf\n",
            "MESSAGE user hello\n",
            "RENDERER gemma4\n",
            "PARSER gemma4\n",
        )
    );
}

#[test]
fn replacement_keeps_real_from_and_unknown_directives() {
    let input = concat!(
        "FROM C:/models/blobs/sha256-base\n",
        "PARAMETER num_ctx 100000\n",
        "LICENSE \"Apache-2.0\"\n",
        "FUTURE_DIRECTIVE enabled\n",
    );
    let entries = vec![
        ("num_ctx".to_string(), "24576".to_string()),
        ("temperature".to_string(), "0.4".to_string()),
    ];

    let output = rewrite(input, &entries).expect("valid parameters");

    assert_eq!(
        output,
        concat!(
            "FROM C:/models/blobs/sha256-base\n",
            "PARAMETER num_ctx 24576\n",
            "PARAMETER temperature 0.4\n",
            "LICENSE \"Apache-2.0\"\n",
            "FUTURE_DIRECTIVE enabled\n",
        )
    );
    assert!(!output.contains("FROM gemma4"));
}

#[test]
fn repeated_text_parameters_follow_ollama_quoting_and_preserve_crlf() {
    let input = "FROM C:/models/blobs/sha256-base\r\nPARAMETER stop \"old\"\r\n";
    let entries = vec![
        ("stop".to_string(), "First".to_string()),
        ("stop".to_string(), "User:".to_string()),
        ("future_option".to_string(), "enabled value".to_string()),
    ];

    let output = rewrite(input, &entries).expect("valid text parameters");

    assert_eq!(
        output,
        concat!(
            "FROM C:/models/blobs/sha256-base\r\n",
            "PARAMETER stop First\r\n",
            "PARAMETER stop User:\r\n",
            "PARAMETER future_option enabled value\r\n",
        )
    );
}

#[test]
fn text_parameters_preserve_quotes_and_windows_backslashes() {
    let input = "FROM C:/models/blobs/sha256-base\nPARAMETER stop old\n";
    let entries = vec![
        ("stop".to_string(), "say \"hi\"".to_string()),
        ("stop".to_string(), r"C:\x".to_string()),
        ("stop".to_string(), "\"\"\" say \"hi\" \"\"\"".to_string()),
    ];

    let output = rewrite(input, &entries).expect("valid text parameters");

    assert_eq!(
        output,
        concat!(
            "FROM C:/models/blobs/sha256-base\n",
            "PARAMETER stop \"\"\"say \"hi\"\"\"\"\n",
            "PARAMETER stop C:\\x\n",
            "PARAMETER stop \"\"\"\"\"\" say \"hi\" \"\"\"\"\"\"\n",
        )
    );
}

#[test]
fn literal_quote_values_are_never_treated_as_modelfile_syntax() {
    let input = "FROM C:/models/blobs/sha256-base\nPARAMETER stop old\n";
    let entries = vec![
        ("stop".to_string(), "\"".to_string()),
        ("stop".to_string(), "\"\"".to_string()),
    ];

    let output = rewrite(input, &entries).expect("literal quotes are valid stop values");

    assert_eq!(
        output,
        concat!(
            "FROM C:/models/blobs/sha256-base\n",
            "PARAMETER stop \"\"\"\"\"\"\"\n",
            "PARAMETER stop \"\"\"\"\"\"\"\"\n",
        )
    );
}

#[test]
fn triple_quoted_parameter_span_is_preserved_while_following_parameters_are_replaced() {
    let input = concat!(
        "FROM x\n",
        "PARAMETER stop \"\"\"\n",
        "end\n",
        "\"\"\"\n",
        "PARAMETER temperature 0.7\n",
    );

    let output = rewrite(input, &[("temperature".into(), "0.4".into())])
        .expect("valid multiline parameter");

    assert_eq!(
        output,
        concat!(
            "FROM x\n",
            "PARAMETER stop \"\"\"\n",
            "end\n",
            "\"\"\"\n",
            "PARAMETER temperature 0.4\n",
        )
    );
}

#[test]
fn simple_quoted_multiline_parameter_span_is_preserved() {
    let input = concat!(
        "FROM x\r\n",
        "PARAMETER stop \"\r\n",
        "end\r\n",
        "\"\r\n",
        "PARAMETER temperature 0.7\r\n",
    );

    let output = rewrite(input, &[("temperature".into(), "0.4".into())])
        .expect("valid multiline parameter");

    assert_eq!(
        output,
        concat!(
            "FROM x\r\n",
            "PARAMETER stop \"\r\n",
            "end\r\n",
            "\"\r\n",
            "PARAMETER temperature 0.4\r\n",
        )
    );
}

#[test]
fn parameter_text_inside_multiline_message_is_preserved() {
    let input = concat!(
        "FROM x\n",
        "MESSAGE user \"\"\"Keep this text.\n",
        "PARAMETER temperature 0.7 is message text.\n",
        "\"\"\"\n",
        "PARAMETER temperature 0.8\n",
    );

    let output = rewrite(input, &[("temperature".into(), "0.4".into())])
        .expect("valid multiline message");

    assert_eq!(
        output,
        concat!(
            "FROM x\n",
            "MESSAGE user \"\"\"Keep this text.\n",
            "PARAMETER temperature 0.7 is message text.\n",
            "\"\"\"\n",
            "PARAMETER temperature 0.4\n",
        )
    );
}

#[test]
fn multimodal_sources_and_runtime_directives_are_preserved() {
    let input = concat!(
        "FROM C:/models/blobs/sha256-model\n",
        "FROM C:/models/blobs/sha256-projector\n",
        "ADAPTER C:/models/blobs/sha256-adapter\n",
        "DRAFT C:/models/blobs/sha256-draft\n",
        "RENDERER gemma4\n",
        "PARSER gemma4\n",
        "PARAMETER temperature 0.8\n",
    );

    let output = rewrite(input, &[("temperature".into(), "0.4".into())])
        .expect("valid multimodal Modelfile");

    assert!(output.contains("FROM C:/models/blobs/sha256-model\n"));
    assert!(output.contains("FROM C:/models/blobs/sha256-projector\n"));
    assert!(output.contains("ADAPTER C:/models/blobs/sha256-adapter\n"));
    assert!(output.contains("DRAFT C:/models/blobs/sha256-draft\n"));
    assert!(output.contains("RENDERER gemma4\n"));
    assert!(output.contains("PARSER gemma4\n"));
    assert!(output.contains("PARAMETER temperature 0.4\n"));
}
