use super::ollama_modelfile_parameters::rewrite;

#[test]
fn empty_entries_remove_every_top_level_parameter() {
    let input = concat!(
        "# generated by Ollama\n",
        "FROM C:/models/blobs/sha256-base\n",
        "SYSTEM \"\"\"Keep this prompt.\n",
        "PARAMETER num_ctx 777 must remain prompt text.\n",
        "\"\"\"\n",
        "PARAMETER num_ctx 100000\n",
        "PARAMETER temperature 0.8\n",
        "ADAPTER ./adapter.gguf\n",
        "MESSAGE user hello\n",
        "RENDERER gemma4\n",
        "PARSER gemma4\n",
    );

    let output = rewrite(input, &[]).expect("valid generated Modelfile");

    assert_eq!(
        output,
        concat!(
            "# generated by Ollama\n",
            "FROM C:/models/blobs/sha256-base\n",
            "SYSTEM \"\"\"Keep this prompt.\n",
            "PARAMETER num_ctx 777 must remain prompt text.\n",
            "\"\"\"\n",
            "ADAPTER ./adapter.gguf\n",
            "MESSAGE user hello\n",
            "RENDERER gemma4\n",
            "PARSER gemma4\n",
        )
    );
}

#[test]
fn replacement_keeps_real_from_and_unknown_directives() {
    let input = concat!(
        "FROM C:/models/blobs/sha256-base\n",
        "PARAMETER num_ctx 100000\n",
        "LICENSE \"Apache-2.0\"\n",
        "FUTURE_DIRECTIVE enabled\n",
    );
    let entries = vec![
        ("num_ctx".to_string(), "24576".to_string()),
        ("temperature".to_string(), "0.4".to_string()),
    ];

    let output = rewrite(input, &entries).expect("valid parameters");

    assert_eq!(
        output,
        concat!(
            "FROM C:/models/blobs/sha256-base\n",
            "PARAMETER num_ctx 24576\n",
            "PARAMETER temperature 0.4\n",
            "LICENSE \"Apache-2.0\"\n",
            "FUTURE_DIRECTIVE enabled\n",
        )
    );
    assert!(!output.contains("FROM gemma4"));
}

#[test]
fn repeated_text_parameters_are_rendered_as_safe_strings() {
    let input = "FROM C:/models/blobs/sha256-base\r\nPARAMETER stop \"old\"\r\n";
    let entries = vec![
        ("stop".to_string(), "First".to_string()),
        ("stop".to_string(), "\"User:\"".to_string()),
        ("future_option".to_string(), "enabled value".to_string()),
    ];

    let output = rewrite(input, &entries).expect("valid text parameters");

    assert_eq!(
        output,
        concat!(
            "FROM C:/models/blobs/sha256-base\r\n",
            "PARAMETER stop \"First\"\r\n",
            "PARAMETER stop \"User:\"\r\n",
            "PARAMETER future_option \"enabled value\"\r\n",
        )
    );
}
