use super::error::OllamaErrorCode;
use super::types::{
    BundleState, CancelOutcome, DaemonState, OllamaEndpoint, OllamaProgressStage,
    OllamaRuntimeStatus, OllamaStartOutcome, OperationState,
};

#[test]
fn checked_in_typescript_matches_the_rust_runtime_contract() {
    let checked_in = include_str!("../../../../src/types/ollama-runtime.ts").replace("\r\n", "\n");
    assert_eq!(checked_in, typescript_bindings());
}

#[test]
fn runtime_contract_serializes_every_public_status_variant() {
    let status = OllamaRuntimeStatus {
        bundle: BundleState::TransactionPending,
        daemon: DaemonState::External {
            endpoint: OllamaEndpoint::loopback(std::num::NonZeroU16::new(11434).unwrap()),
        },
        operation: OperationState::Updating,
        progress: Some(OllamaProgressStage::Validating),
        last_error: Some(OllamaErrorCode::OllamaValidationDeferred),
    };
    let value = serde_json::to_value(status).unwrap();
    assert_eq!(value["bundle"], "transaction_pending");
    assert_eq!(value["daemon"]["external"]["endpoint"]["port"], 11434);
    assert_eq!(value["operation"], "updating");
    assert_eq!(value["progress"], "validating");
    assert_eq!(value["last_error"], "ollama-validation-deferred");
}

#[test]
fn runtime_contract_keeps_start_and_cancel_outcomes_typed() {
    let start = OllamaStartOutcome::RejectedDuringShutdown;
    let cancel = CancelOutcome::RejectedDuringShutdown;
    assert_eq!(serde_json::to_value(start).unwrap(), "rejected_during_shutdown");
    assert_eq!(serde_json::to_value(cancel).unwrap(), "rejected_during_shutdown");
}

#[test]
#[ignore = "developer command that refreshes the checked-in TypeScript contract"]
fn export_typescript_runtime_contract() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/types/ollama-runtime.ts");
    std::fs::write(path, typescript_bindings()).unwrap();
}

fn typescript_bindings() -> String {
    use ts_rs::{Config, TS};

    let config = Config::default();
    format!(
        "// @generated from Rust by `npm run contracts:generate:ollama`.\n\
         // Do not edit this file manually.\n\n\
         export {}\n\n\
         export {}\n\n\
         export {}\n\n\
         export {}\n\n\
         export {}\n\n\
         export {}\n\n\
         export {}\n\n\
         export {}\n\n\
         export {}\n",
        BundleState::decl(&config),
        DaemonState::decl(&config),
        OperationState::decl(&config),
        OllamaProgressStage::decl(&config),
        OllamaErrorCode::decl(&config),
        OllamaEndpoint::decl(&config),
        OllamaStartOutcome::decl(&config),
        CancelOutcome::decl(&config),
        OllamaRuntimeStatus::decl(&config),
    )
}
