pub const MAX_USER_PRIORITY_PLUGINS: usize = 15;
pub const MAX_SELF_DECLARED_ESSENTIAL_PLUGINS: usize = 15;
pub const MAX_CATALOG_DESCRIPTION_CHARS: usize = 240;
pub const CATALOG_USAGE_ORDER_THRESHOLD_BYTES: usize = 16 * 1024;
pub const DISCOVERY_STORE_MAX_BYTES: u64 = 64 * 1024;
