// @generated from Rust by `npm run contracts:generate:diagnostics`.
// Do not edit this file manually.

import type { ToolErrorCategory, ToolResultStatus } from "./agent-tool-result";

export type AgentDiagnosticTool = { name: string, status: string, args?: unknown, is_error: boolean, result_status?: ToolResultStatus, error_code?: string, error_category?: ToolErrorCategory, retryable?: boolean, truncated: boolean, warning_count: number, };

export type AgentDiagnosticTodo = { id: string, title: string, active_task?: string, completed: number, total: number, progress: string, };

export type AgentDiagnosticEvent = { at: string, phase: string, message: string, tool_name?: string, error_type?: string, };

export type AgentDiagnosticRun = { request_id: string, generation: number, status: string, severity: string, started_at: string, updated_at: string, ended_at?: string, phase: string, error_type?: string, last_tool?: AgentDiagnosticTool, recent_tools?: Array<AgentDiagnosticTool>, active_todo?: AgentDiagnosticTodo, safe_summary?: string, events?: Array<AgentDiagnosticEvent>, };
