// @generated from Rust by `npm run contracts:generate:agent`.
// Do not edit this file manually.

export type TurnAttachmentInput = { name: string, path: string, mime_type: string, size: number, thumbnail?: string, access_grant?: string, };

export type SkillReference = { id: string, name?: string, };

export type NewUserTurnInput = { content: string, files: Array<TurnAttachmentInput>, skills: Array<SkillReference>, };

export type ResumeTurnInput = { message_id: string, };
