// @generated from Rust by `npm run contracts:generate:agent`.
// Do not edit this file manually.

export type TurnAttachmentInput = { name: string, path: string, mime_type: string, size: number, thumbnail?: string, access_grant?: string, };

export type SkillReference = { id: string, name?: string, };

export type NewUserTurnInput = { content: string, files: Array<TurnAttachmentInput>, skills: Array<SkillReference>, };

export type ResumeTurnInput = { message_id: string, };

export type TurnStart = { "type": "new", "input": NewUserTurnInput } | { "type": "resume", "input": ResumeTurnInput };

export type ChatStreamRequestInput = { sessionId: string, model: string, provider: string, turn: TurnStart, workingDir: string | null, permissionMode: string | null, planMode: boolean | null, };

export type ChatStreamAdmission = { generation: number, turnId: string, userMessageId: string, assistantMessageId: string, };
