// @generated from Rust by `npm run contracts:generate`.
// Do not edit this file manually.

export type ProviderCategory = "llm" | "search" | "scraping" | "forecast";

export type ProviderCatalogEntry = { id: string, display_name: string, category: ProviderCategory, signup_url: string, base_url?: string, models_endpoint?: string, };

export type ProviderSpec = ProviderCatalogEntry;
