// @generated from Rust by `npm run contracts:generate:compression`.
// Do not edit this file manually.

export type CompressionWindowBand = "under_64k" | "compact" | "large";

export type CompressionTrigger = "automatic" | "explicit";

export type CompressionBandSettings = { recent_message_count: number, summary_max_tokens: number, tool_result_count: number, recent_file_count: number, image_count: number, include_work_state: boolean, };

export type CompressionProfile = { id: string, name: string, revision: number, threshold_percent: number, allow_under_64k: boolean, system_prompt: string, handoff_prompt: string, under_64k: CompressionBandSettings, compact: CompressionBandSettings, large: CompressionBandSettings, };

export type CompressionProfileInput = { id: string, name: string, revision: number, threshold_percent: number, allow_under_64k: boolean, system_prompt: string, handoff_prompt: string, under_64k: CompressionBandSettings, compact: CompressionBandSettings, large: CompressionBandSettings, };

export type CompressionProfilesView = { automatic_enabled: boolean, global_profile_id: string, global_selection_revision: number, profiles: Array<CompressionProfile>, };

export type BudgetProjectionView = { band: CompressionWindowBand, before_tokens: number, system_tools_tokens: number, variable_tokens: number, target_tokens: number, range_lower_tokens: number, range_upper_tokens: number, image_count: number, projected_percent: number, };

export type CompressionDeleteResult = { view: CompressionProfilesView, undo_token: string, undo_expires_in_ms: number, };

export type ResolvedCompressionProfileSource = "global" | "session";

export type ResolvedCompressionProfileView = { id: string, name: string, source: ResolvedCompressionProfileSource, profile_revision: number, global_selection_revision: number, context_window: number, band: CompressionWindowBand | null, available: boolean, };

export type CompressionProfileView = CompressionProfile;
export type CompressionBandView = CompressionBandSettings;
