// @generated from Rust by `npm run contracts:generate:model-downloads`.
// Do not edit this file manually.

export type ModelDownloadKind = "ollama" | "forecast" | "voice";

export type ModelDownloadStatus = "queued" | "running" | "cancelling" | "completed" | "failed" | "cancelled" | "suspended";

export type ModelDownloadPhase = "starting" | "downloading" | "preparing-runtime" | "installing" | "completed";

export type ModelDownloadState = { id: string, kind: ModelDownloadKind, modelId: string, isUpdate: boolean, status: ModelDownloadStatus, phase: ModelDownloadPhase, percent: number, downloaded: number, total: number, errorKey: string | null, };
