// @generated from Rust by `cargo test services::llm::model_reasoning_contract_tests::export_typescript_model_reasoning_contract -- --ignored --exact`.
// Do not edit this file manually.

export type ReasoningModeId = "off" | "auto" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max" | "ultra";

export type ReasoningControl = { "kind": "unknown" } | { "kind": "provider_default" } | { "kind": "toggle" } | { "kind": "efforts", "efforts": Array<ReasoningModeId> };

export type ModelReasoningContract = { mandatory?: boolean, default_enabled?: boolean, supports_max_tokens?: boolean, default_effort?: ReasoningModeId, control: ReasoningControl, };
