// @generated from Rust by `npm run contracts:generate:ollama`.
// Do not edit this file manually.

export type BundleState = "absent" | "ready" | "transaction_pending" | "recovery_required";

export type DaemonState = "unavailable" | { "owned": { endpoint: OllamaEndpoint, } } | { "external": { endpoint: OllamaEndpoint, } };

export type OperationState = "idle" | "installing" | "updating" | "recovering" | "cancelling";

export type OllamaProgressStage = "preparing" | "downloading" | "verifying" | "extracting" | "validating" | "committing" | "starting" | "recovering" | "rolling_back" | "cleaning";

export type OllamaErrorCode = "ollama-update-cleanup-pending" | "ollama-update-recovery-required" | "ollama-recovery-deferred" | "ollama-model-store-conflict" | "ollama-storage-unavailable" | "ollama-journal-invalid" | "ollama-bundle-missing" | "ollama-bundle-invalid" | "ollama-download-failed" | "ollama-checksum-mismatch" | "ollama-extraction-failed" | "ollama-validation-deferred" | "ollama-operation-in-progress" | "ollama-operation-cancelled" | "ollama-closing" | "ollama-start-failed" | "ollama-stop-failed" | "ollama-setup-timeout" | "ollama-unavailable" | "ollama-internal";

export type OllamaEndpoint = { port: number, };

export type OllamaStartOutcome = { "owned_started": { endpoint: OllamaEndpoint, } } | { "owned_already_running": { endpoint: OllamaEndpoint, } } | { "external_available": { endpoint: OllamaEndpoint, } } | "rejected_during_shutdown" | { "blocked_by_recovery": { code: OllamaErrorCode, } } | { "failed": { code: OllamaErrorCode, } };

export type CancelOutcome = "cancelled" | "already_idle" | "rejected_during_shutdown";

export type OllamaRuntimeStatus = { bundle: BundleState, daemon: DaemonState, operation: OperationState, progress: OllamaProgressStage | null, last_error: OllamaErrorCode | null, };
