// @generated by Rust terminal_contract_tests. Do not edit.

export type TerminalSavedTab = { label: string, };
export type TerminalTabsDocument = { version: number, groups: { [key in string]: Array<TerminalSavedTab> }, };
export const TERMINAL_TABS_VERSION = 1 as const;
export const MAX_LIVE_TERMINALS = 16;
export const MAX_GROUPS = 128;
export const MAX_TABS_PER_GROUP = 16;
export const MAX_TOTAL_TABS = 256;
export const MAX_GROUP_KEY_BYTES = 128;
export const MAX_LABEL_BYTES = 512;
export const MAX_WRITE_BYTES = 65536;
export const MAX_FRAME_BYTES = 65536;
export const MAX_IN_FLIGHT_BYTES = 1048576;
