// @generated from Rust by `npm run contracts:generate:update-progress`.
// Do not edit this file manually.

export type UpdateOperationKind = "app-release" | "ollama-binary" | "ollama-model" | "forecast-model";

export type UpdateOperationStatus = "queued" | "running" | "cancelling" | "completed" | "failed" | "cancelled";

export type UpdateOperationPhase = "waiting" | "preparing" | "downloading" | "verifying" | "extracting" | "installing" | "restarting" | "recovering" | "rolling-back" | "cleaning" | "completed";

export type UpdateProgressMode = "none" | "indeterminate" | "determinate";

export type UpdateOperationSnapshot = { id: string, sequence: number, kind: UpdateOperationKind, label: string, status: UpdateOperationStatus, phase: UpdateOperationPhase, progressMode: UpdateProgressMode, percent: number | null, queuePosition: number | null, canCancel: boolean, canRetry: boolean, isUpdate: boolean | null, errorKey: string | null, };
