// @generated from Rust by `npm run contracts:generate:voice`.
// Do not edit this file manually.

export type VoicePhase = "idle" | "preparing" | "listening" | "transcribing" | "recovering" | "stopping" | "delivering";

export type VoiceModel = "parakeet-tdt-v3" | "cohere-transcribe" | "qwen3-asr06b";

export type VoiceInputDevice = { "kind": "system-default" } | { "kind": "device", "value": string };

export type VoiceSilenceTimeout = "three-seconds" | "five-seconds" | "ten-seconds" | "twenty-seconds" | "thirty-seconds" | "never";

export type VoiceMaxDuration = "2-minutes" | "5-minutes" | "10-minutes" | "20-minutes" | "30-minutes";

export type VoiceLanguage = { "kind": "follow-interface" } | { "kind": "automatic" } | { "kind": "language", "value": string };

export type VoiceUnloadDelay = "immediately" | "one-minute" | "two-minutes" | "five-minutes" | "fifteen-minutes" | "on-exit";

export type VoiceSettings = { version: number, enabled: boolean, model: VoiceModel, input_device: VoiceInputDevice, silence_timeout: VoiceSilenceTimeout, max_duration: VoiceMaxDuration, language: VoiceLanguage, shortcut: string | null, unload_delay: VoiceUnloadDelay, explanation_accepted: boolean, };

export type VoiceSettingsPatch = { enabled?: boolean, model?: VoiceModel, input_device?: VoiceInputDevice, silence_timeout?: VoiceSilenceTimeout, max_duration?: VoiceMaxDuration, language?: VoiceLanguage, shortcut?: string | null, unload_delay?: VoiceUnloadDelay, explanation_accepted?: boolean, };

export type VoiceDestination = { "kind": "draft", draft_key: string, } | { "kind": "trial", trial_id: string, };

export type VoiceDeliveryOutcome = "inserted" | "already-inserted" | "closed";

export type VoiceAction = { "action": "start", destination: VoiceDestination, context_generation: number, language: VoiceLanguage | null, } | { "action": "validate", operation_id: string, } | { "action": "cancel-insertion", operation_id: string, } | { "action": "abandon-trial", trial_id: string, } | { "action": "delete-recovery", recovery_id: string, } | { "action": "restore-recovery", recovery_id: string, draft_key: string, } | { "action": "acknowledge-delivery", result_id: string, outcome: VoiceDeliveryOutcome, } | { "action": "destination-closed", destination: VoiceDestination, } | { "action": "message-accepted", draft_key: string, send_id: string, } | { "action": "install", model_id: string, } | { "action": "resume", transfer_id: string, } | { "action": "cancel-download", transfer_id: string, } | { "action": "uninstall", model_id: string, };

export type VoiceDevice = { id: string, name: string, };

export type VoiceCatalogItem = { id: string, model: VoiceModel | null, installed: boolean, downloadBytes: number, installedBytes: number, languages: Array<string>, dialects: Array<string>, automaticOnly: boolean, };

export type VoiceOperationSnapshot = { id: string, destination: VoiceDestination, contextGeneration: number, captureMs: number, speechMs: number, captureIncomplete: boolean, level: number, };

export type VoiceRecoverySnapshot = { id: string, draftKey: string | null, captureMs: number, status: VoiceRecoveryState, };

export type VoiceRecoveryState = "preparing" | "ready" | "failed";

export type VoiceDeliverySnapshot = { id: string, draftKey: string, text: string, };

export type VoiceTrialResult = { trialId: string, text: string, captureMs: number, computeMs: number, };

export type VoiceSnapshot = { revision: number, phase: VoicePhase, operation: VoiceOperationSnapshot | null, recovery: VoiceRecoverySnapshot | null, delivery: VoiceDeliverySnapshot | null, trialResult: VoiceTrialResult | null, error: VoiceError | null, };

export type VoiceErrorCode = "busy" | "shutting-down" | "invalid-settings" | "configuration-unavailable" | "invalid-transition";

export type VoiceErrorParamKey = "required-bytes" | "available-bytes";

export type VoiceErrorParam = { key: VoiceErrorParamKey, value: string, };

export type VoiceError = { code: VoiceErrorCode, params: Array<VoiceErrorParam>, };

export type VoiceProjection = { phase: VoicePhase, error: VoiceError | null, };
