// @generated from Rust by `npm run contracts:generate:voice`.
// Do not edit this file manually.

export type VoicePhase = "idle" | "preparing" | "listening" | "transcribing" | "recovering" | "stopping" | "delivering";

export type VoiceModel = "parakeet-tdt-v3" | "cohere-transcribe" | "qwen3-asr06b";

export type VoiceInputDevice = { "kind": "system-default" } | { "kind": "device", "value": string };

export type VoiceSilenceTimeout = "three-seconds" | "five-seconds" | "ten-seconds" | "twenty-seconds" | "thirty-seconds" | "never";

export type VoiceMaxDuration = "2-minutes" | "5-minutes" | "10-minutes" | "20-minutes" | "30-minutes";

export type VoiceLanguage = { "kind": "follow-interface" } | { "kind": "automatic" } | { "kind": "language", "value": string };

export type VoiceUnloadDelay = "immediately" | "one-minute" | "two-minutes" | "five-minutes" | "fifteen-minutes" | "on-exit";

export type VoiceSettings = { version: number, enabled: boolean, model: VoiceModel, input_device: VoiceInputDevice, silence_timeout: VoiceSilenceTimeout, max_duration: VoiceMaxDuration, language: VoiceLanguage, shortcut: string | null, unload_delay: VoiceUnloadDelay, explanation_accepted: boolean, };

export type VoiceSettingsPatch = { enabled?: boolean, model?: VoiceModel, input_device?: VoiceInputDevice, silence_timeout?: VoiceSilenceTimeout, max_duration?: VoiceMaxDuration, language?: VoiceLanguage, shortcut?: string | null, unload_delay?: VoiceUnloadDelay, explanation_accepted?: boolean, };

export type VoiceErrorCode = "busy" | "shutting-down" | "invalid-settings" | "configuration-unavailable" | "invalid-transition";

export type VoiceErrorParamKey = "required-bytes" | "available-bytes";

export type VoiceErrorParam = { key: VoiceErrorParamKey, value: string, };

export type VoiceError = { code: VoiceErrorCode, params: Array<VoiceErrorParam>, };

export type VoiceProjection = { phase: VoicePhase, error: VoiceError | null, };
