// @generated by Rust browser_contract_tests. Do not edit.

export type BrowserTabState = { id: string, title: string, url: string | null, loading: boolean, canGoBack: boolean, canGoForward: boolean, released: boolean, };
export type BrowserSessionState = { tabs: Array<BrowserTabState>, activeTabId: string, generation: number, };
export type BrowserTabCreation = { "status": "created", session: BrowserSessionState, } | { "status": "confirmationRequired", candidateId: string, candidateTitle: string, };
export type LocalSiteProtocol = "http" | "https";
export type LocalSite = { url: string, title: string, port: number, protocol: LocalSiteProtocol, };
export type LocalSiteScanResult = { sites: Array<LocalSite>, generation: number, changed: boolean, };
export type BrowserTabEvent = { eventVersion: number, generation: number, conversationId: string, tabId: string, };
export type PopupRequestEvent = { eventVersion: number, generation: number, conversationId: string, sourceTabId: string, url: string, };
export type BrowserSessionEvent = { eventVersion: number, conversationId: string, session: BrowserSessionState, };
export const BROWSER_EVENT_VERSION = 1;
export const MAX_BROWSER_TABS = 10;
export const MAX_BROWSER_TITLE_CHARS = 80;
export const MAX_BROWSER_URL_LENGTH = 2048;
export const MAX_BROWSER_SURFACE_EDGE = 16384;
export const MAX_LOCAL_SITES = 32;
export const MAX_LOCAL_TITLE_CHARS = 80;
