// @generated by Rust favicon_contract_tests::export_favicon_contract. Do not edit.

export type BrowserFaviconIcon = { tabId: string, pngBase64: string, };
export type BrowserFaviconSnapshot = { eventVersion: number, revision: number, conversationId: string, icons: Array<BrowserFaviconIcon>, };
export const FAVICON_EVENT = "browser-favicons-changed-v1";
export const FAVICON_EVENT_VERSION = 1;
export const MAX_FAVICONS = 10;
export const MAX_FAVICON_PNG_BYTES = 32768;
