use serde::{Deserialize, Deserializer, Serialize};

pub const MAX_TURN_ATTACHMENTS: usize = 15;
pub const MAX_SKILLS_PER_TURN: usize = 8;
pub const MAX_TURN_CONTENT_BYTES: usize = 1024 * 1024;
pub const MAX_TURN_IMAGE_BYTES: usize = 20 * 1024 * 1024;
pub const MAX_ATTACHMENT_NAME_BYTES: usize = 1024;
pub const MAX_ATTACHMENT_PATH_BYTES: usize = 4096;
pub const MAX_ATTACHMENT_MIME_BYTES: usize = 128;
pub const MAX_ATTACHMENT_GRANT_BYTES: usize = 128;
pub const MAX_ATTACHMENT_THUMBNAIL_BYTES: usize = MAX_TURN_IMAGE_BYTES.div_ceil(3) * 4 + 96;
pub const MAX_SKILL_ID_BYTES: usize = 768;
pub const MAX_SKILL_NAME_BYTES: usize = 480;
pub const MAX_RESUME_MESSAGE_ID_BYTES: usize = 64;

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
pub struct TurnAttachmentInput {
    pub name: String,
    pub path: String,
    pub mime_type: String,
    #[cfg_attr(test, ts(type = "number"))]
    pub size: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub thumbnail: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub access_grant: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
pub struct SkillReference {
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub name: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
pub struct NewUserTurnInput {
    pub content: String,
    pub files: Vec<TurnAttachmentInput>,
    pub skills: Vec<SkillReference>,
}

#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
pub struct ResumeTurnInput {
    pub message_id: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(tag = "type", content = "input", rename_all = "camelCase")]
#[cfg_attr(test, derive(ts_rs::TS))]
pub enum TurnStart {
    New(NewUserTurnInput),
    Resume(ResumeTurnInput),
}

impl<'de> Deserialize<'de> for TurnStart {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        super::agent_turn_contract_wire::turn_start(deserializer)
    }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(test, derive(ts_rs::TS))]
pub struct ChatStreamAdmission {
    #[cfg_attr(test, ts(type = "number"))]
    pub generation: u64,
    pub turn_id: String,
    pub user_message_id: String,
    pub assistant_message_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ChatStreamRequestInput {
    pub session_id: String,
    pub model: String,
    pub provider: String,
    pub turn: TurnStart,
    pub working_dir: Option<String>,
    pub permission_mode: Option<String>,
    pub plan_mode: Option<bool>,
}

impl<'de> Deserialize<'de> for NewUserTurnInput {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        super::agent_turn_contract_wire::new_turn(deserializer)
    }
}

impl<'de> Deserialize<'de> for TurnAttachmentInput {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        super::agent_turn_contract_wire::attachment(deserializer)
    }
}

impl<'de> Deserialize<'de> for SkillReference {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        super::agent_turn_contract_wire::skill(deserializer)
    }
}

impl<'de> Deserialize<'de> for ResumeTurnInput {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        super::agent_turn_contract_wire::resume(deserializer)
    }
}

#[cfg(test)]
pub(crate) fn typescript_bindings() -> String {
    use ts_rs::{Config, TS};

    let config = Config::default();
    let declarations = [
        TurnAttachmentInput::decl(&config),
        SkillReference::decl(&config),
        NewUserTurnInput::decl(&config),
        ResumeTurnInput::decl(&config),
        TurnStart::decl(&config),
        ChatStreamRequestInput::decl(&config),
        ChatStreamAdmission::decl(&config),
    ];
    format!(
        "// @generated from Rust by `npm run contracts:generate:agent`.\n\
         // Do not edit this file manually.\n\n\
         export {}\n",
        declarations.join("\n\nexport ")
    )
}
