use serde_json::json;

use super::agent_session_contract::{
    typescript_bindings, EditUserMessageInput, SessionMetadataPatch,
};

#[test]
fn metadata_patch_rejects_messages_and_unknown_fields() {
    assert!(serde_json::from_value::<SessionMetadataPatch>(json!({
        "name": "Session visible",
        "messages": []
    }))
    .is_err());
    assert!(serde_json::from_value::<SessionMetadataPatch>(json!({
        "continuation": {"encrypted_content": "opaque"}
    }))
    .is_err());
}

#[test]
fn edit_input_exposes_only_the_target_and_new_content() {
    let input: EditUserMessageInput = serde_json::from_value(json!({
        "message_id": "00000000-0000-4000-8000-000000000001",
        "new_content": "Texte visible"
    }))
    .expect("visible edit input");

    assert_eq!(input.message_id, "00000000-0000-4000-8000-000000000001");
    assert_eq!(input.new_content, "Texte visible");
    assert!(serde_json::from_value::<EditUserMessageInput>(json!({
        "message_id": "00000000-0000-4000-8000-000000000001",
        "new_content": "Texte visible",
        "tool_call_id": "forged-call",
        "segments": []
    }))
    .is_err());
}

#[test]
fn checked_in_agent_session_types_match_rust() {
    let checked_in =
        include_str!("../../../src/types/agent-session.generated.ts").replace("\r\n", "\n");

    assert_eq!(checked_in, typescript_bindings());
    assert!(checked_in.contains("Do not edit this file manually"));
}

#[test]
#[ignore = "developer command that refreshes the checked-in TypeScript contract"]
fn export_typescript_agent_session_contract() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../src/types/agent-session.generated.ts");

    std::fs::write(path, typescript_bindings()).unwrap();
}
