use serde::{Deserialize, Serialize};

#[path = "agent_message_view_contract.rs"]
mod message;
#[path = "agent_session_view_contract.rs"]
mod session;

pub use message::{
    AgentMessageView, FileAttachmentView, SavedSegmentView, ToolActivityRecordView,
    ToolCallFunctionView, ToolCallRequestView, ToolFileChangeView,
};
pub use session::{
    AgentSessionView, AgentStreamFailureView, ContinuityCapability, ContinuityRequirement,
    ContinuityState, SubagentLastActivityView,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "snake_case")]
#[cfg_attr(test, ts(rename_all = "snake_case"))]
pub enum ReasoningReplayStatus {
    Unavailable,
    Partial,
    Preserved,
    Compacted,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(default, deny_unknown_fields)]
pub struct SessionMetadataPatch {
    #[cfg_attr(test, ts(optional))]
    pub name: Option<String>,
    #[cfg_attr(test, ts(optional))]
    pub model: Option<String>,
    #[cfg_attr(test, ts(optional))]
    pub provider: Option<String>,
    #[cfg_attr(test, ts(optional))]
    pub reasoning_mode: Option<String>,
    #[cfg_attr(test, ts(optional))]
    pub fast_mode_enabled: Option<bool>,
    #[cfg_attr(test, ts(optional))]
    pub project_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(deny_unknown_fields)]
pub struct EditUserMessageInput {
    pub message_id: String,
    pub new_content: String,
}

#[cfg(test)]
pub(crate) fn typescript_bindings() -> String {
    use ts_rs::{Config, TS};

    let config = Config::default();
    let declarations = [
        crate::services::agent_local::types_session::PreserveReasoningSetting::decl(&config),
        ReasoningReplayStatus::decl(&config),
        message::FileAttachmentView::decl(&config),
        message::ToolCallFunctionView::decl(&config),
        message::ToolCallRequestView::decl(&config),
        message::ToolFileChangeView::decl(&config),
        message::ToolActivityRecordView::decl(&config),
        message::SavedSegmentView::decl(&config),
        message::AgentMessageView::decl(&config),
        session::SubagentLastActivityView::decl(&config),
        session::AgentStreamFailureView::decl(&config),
        session::ContinuityRequirement::decl(&config),
        session::ContinuityState::decl(&config),
        session::ContinuityCapability::decl(&config),
        session::AgentSessionView::decl(&config),
        SessionMetadataPatch::decl(&config),
        EditUserMessageInput::decl(&config),
    ];
    format!(
        "// @generated from Rust by `npm run contracts:generate:agent`.\n\
         // Do not edit this file manually.\n\n\
         import type {{ AgentDiagnosticRun }} from \"./agent-diagnostics\";\n\
         import type {{ AgentPlanRun, AgentPlanWorkflowStatus }} from \"./agent-plan\";\n\
         import type {{ PersistedToolResultMeta }} from \"./agent-tool-result\";\n\
         import type {{ AgentTodoItem, AgentTodoRun }} from \"./agent-todo\";\n\
         import type {{ GitDiffPreview }} from \"./file-preview\";\n\n\
         export {}\n",
        declarations.join("\n\nexport ")
    )
}
