use serde::Serialize;

#[derive(Debug, Clone, Copy, Eq, PartialEq, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "lowercase")]
#[cfg_attr(test, ts(rename_all = "lowercase"))]
pub enum ProviderCategory {
    Llm,
    Search,
    Scraping,
    Forecast,
}

impl ProviderCategory {
    pub fn from_wire(value: &str) -> Option<Self> {
        match value {
            "llm" => Some(Self::Llm),
            "search" => Some(Self::Search),
            "scraping" => Some(Self::Scraping),
            "forecast" => Some(Self::Forecast),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Eq, PartialEq, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
pub struct ProviderCatalogEntry {
    pub id: String,
    pub display_name: String,
    pub category: ProviderCategory,
    pub signup_url: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub base_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub models_endpoint: Option<String>,
}

impl ProviderCatalogEntry {
    pub fn new(
        id: &str,
        display_name: &str,
        category: ProviderCategory,
        signup_url: &str,
        base_url: Option<&str>,
        models_endpoint: Option<&str>,
    ) -> Self {
        Self {
            id: id.to_string(),
            display_name: display_name.to_string(),
            category,
            signup_url: signup_url.to_string(),
            base_url: base_url.map(str::to_string),
            models_endpoint: models_endpoint.map(str::to_string),
        }
    }
}

#[cfg(test)]
pub(crate) fn typescript_bindings() -> String {
    use ts_rs::{Config, TS};

    let config = Config::default();

    format!(
        "// @generated from Rust by `npm run contracts:generate`.\n\
         // Do not edit this file manually.\n\n\
         export {}\n\n\
         export {}\n\n\
         export type ProviderSpec = ProviderCatalogEntry;\n",
        ProviderCategory::decl(&config),
        ProviderCatalogEntry::decl(&config)
    )
}
