#[cfg(test)]
pub(crate) fn typescript_bindings() -> String {
    use crate::services::voice::contracts::*;
    use crate::services::voice::download::VoiceLanguageMode;
    use crate::services::voice::errors::{VoiceError, VoiceErrorCode};
    use crate::services::voice::types::*;
    use ts_rs::{Config, TS};

    let config = Config::default();
    let declarations = [
        VoiceLanguageMode::decl(&config),
        VoicePhase::decl(&config),
        VoiceModel::decl(&config),
        VoiceInputDevice::decl(&config),
        VoiceInputGain::decl(&config),
        VoiceSilenceTimeout::decl(&config),
        VoiceMaxDuration::decl(&config),
        VoiceLanguage::decl(&config),
        VoiceUnloadDelay::decl(&config),
        VoiceSettings::decl(&config),
        VoiceSettingsPatch::decl(&config),
        VoiceDestination::decl(&config),
        VoiceDeliveryOutcome::decl(&config),
        VoiceAction::decl(&config),
        VoiceDevice::decl(&config),
        VoiceCatalogItem::decl(&config),
        VoiceOperationSnapshot::decl(&config),
        VoiceRecoverySnapshot::decl(&config),
        VoiceRecoveryState::decl(&config),
        VoiceDeliverySnapshot::decl(&config),
        VoiceTrialResult::decl(&config),
        VoiceSnapshot::decl(&config),
        VoiceErrorCode::decl(&config),
        VoiceError::decl(&config),
    ];
    format!(
        "// @generated from Rust by `npm run contracts:generate:voice`.\n\
         // Do not edit this file manually.\n\n\
         export {}\n",
        declarations.join("\n\nexport ")
    )
    .lines()
    .map(str::trim_end)
    .collect::<Vec<_>>()
    .join("\n")
        + "\n"
}
