// La projection est publiée par les commandes vocales ajoutées en T09.
#![allow(dead_code)]

use serde::Serialize;

use crate::services::voice::errors::VoiceError;
use crate::services::voice::types::VoicePhase;

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
pub struct VoiceProjection {
    pub phase: VoicePhase,
    pub error: Option<VoiceError>,
}

impl VoiceProjection {
    pub fn idle_error(error: VoiceError) -> Self {
        Self {
            phase: VoicePhase::Idle,
            error: Some(error),
        }
    }
}

#[cfg(test)]
pub(crate) fn typescript_bindings() -> String {
    use crate::services::voice::contracts::*;
    use crate::services::voice::errors::{
        VoiceError, VoiceErrorCode, VoiceErrorParam, VoiceErrorParamKey,
    };
    use crate::services::voice::types::*;
    use ts_rs::{Config, TS};

    let config = Config::default();
    let declarations = [
        VoicePhase::decl(&config),
        VoiceModel::decl(&config),
        VoiceInputDevice::decl(&config),
        VoiceSilenceTimeout::decl(&config),
        VoiceMaxDuration::decl(&config),
        VoiceLanguage::decl(&config),
        VoiceUnloadDelay::decl(&config),
        VoiceSettings::decl(&config),
        VoiceSettingsPatch::decl(&config),
        VoiceDestination::decl(&config),
        VoiceDeliveryOutcome::decl(&config),
        VoiceAction::decl(&config),
        VoiceDevice::decl(&config),
        VoiceCatalogItem::decl(&config),
        VoiceOperationSnapshot::decl(&config),
        VoiceRecoverySnapshot::decl(&config),
        VoiceRecoveryState::decl(&config),
        VoiceDeliverySnapshot::decl(&config),
        VoiceTrialResult::decl(&config),
        VoiceSnapshot::decl(&config),
        VoiceErrorCode::decl(&config),
        VoiceErrorParamKey::decl(&config),
        VoiceErrorParam::decl(&config),
        VoiceError::decl(&config),
        VoiceProjection::decl(&config),
    ];
    format!(
        "// @generated from Rust by `npm run contracts:generate:voice`.\n\
         // Do not edit this file manually.\n\n\
         export {}\n",
        declarations.join("\n\nexport ")
    )
    .lines()
    .map(str::trim_end)
    .collect::<Vec<_>>()
    .join("\n")
        + "\n"
}
