use serde::{Deserialize, Serialize};

pub const MAX_PENDING_DOWNLOADS: usize = 16;
pub const EVENT_NAME: &str = "model-downloads-changed";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "lowercase")]
pub enum ModelDownloadKind {
    Ollama,
    Forecast,
    Voice,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "lowercase")]
pub enum ModelDownloadStatus {
    Queued,
    Running,
    Cancelling,
    Completed,
    Failed,
    Cancelled,
    Suspended,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "kebab-case")]
pub enum ModelDownloadPhase {
    Starting,
    Downloading,
    PreparingRuntime,
    Installing,
    Completed,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
pub struct ModelDownloadState {
    pub id: String,
    pub kind: ModelDownloadKind,
    pub model_id: String,
    pub is_update: bool,
    pub status: ModelDownloadStatus,
    pub phase: ModelDownloadPhase,
    pub percent: u8,
    #[cfg_attr(test, ts(type = "number"))]
    pub downloaded: u64,
    #[cfg_attr(test, ts(type = "number"))]
    pub total: u64,
    pub error_key: Option<String>,
}

#[cfg(test)]
pub(crate) fn typescript_bindings() -> String {
    use ts_rs::{Config, TS};

    let config = Config::default();
    let declarations = [
        ModelDownloadKind::decl(&config),
        ModelDownloadStatus::decl(&config),
        ModelDownloadPhase::decl(&config),
        ModelDownloadState::decl(&config),
    ];
    format!(
        "// @generated from Rust by `npm run contracts:generate:model-downloads`.\n\
         // Do not edit this file manually.\n\n\
         export {}\n",
        declarations.join("\n\nexport ")
    )
    .lines()
    .map(str::trim_end)
    .collect::<Vec<_>>()
    .join("\n")
        + "\n"
}

impl ModelDownloadState {
    pub fn new(
        kind: ModelDownloadKind,
        model_id: String,
        is_update: bool,
        id: String,
        status: ModelDownloadStatus,
    ) -> Self {
        Self {
            id,
            kind,
            model_id,
            is_update,
            status,
            phase: ModelDownloadPhase::Starting,
            percent: 0,
            downloaded: 0,
            total: 0,
            error_key: None,
        }
    }
}
