use serde::Serialize;

#[derive(Debug, Clone, Copy, Eq, PartialEq, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
#[cfg_attr(test, ts(rename_all = "camelCase"))]
pub enum InstallerPhase {
    Ready,
    Checking,
    Downloading,
    Verifying,
    Installing,
    Finishing,
    Cancelling,
    Cancelled,
    Failed,
    Completed,
}

#[derive(Debug, Clone, Copy, Eq, PartialEq, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
#[cfg_attr(test, ts(rename_all = "camelCase"))]
pub enum ProgressMode {
    Determinate,
    Indeterminate,
}

#[derive(Debug, Clone, Copy, Eq, PartialEq, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
#[cfg_attr(test, ts(rename_all = "camelCase"))]
pub enum InstallerOutcome {
    Installed,
    Reinstalled,
}

#[derive(Debug, Clone, Eq, PartialEq, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
#[cfg_attr(test, ts(rename_all = "camelCase"))]
pub struct InstallerSnapshot {
    pub version: String,
    pub destination: String,
    pub installed_version: Option<String>,
    pub beaver_running: bool,
    pub phase: InstallerPhase,
    pub step_index: u8,
    pub step_count: u8,
    pub progress_mode: ProgressMode,
    pub percent: Option<u8>,
    pub can_cancel: bool,
    pub outcome: Option<InstallerOutcome>,
    pub error_key: Option<String>,
}

#[derive(Debug, Clone, Eq, PartialEq, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[serde(rename_all = "camelCase")]
#[cfg_attr(test, ts(rename_all = "camelCase"))]
pub struct InstallerEvent {
    #[cfg_attr(test, ts(type = "number"))]
    pub sequence: u64,
    pub snapshot: InstallerSnapshot,
    #[cfg_attr(test, ts(type = "number[]"))]
    pub completed_step_durations_ms: Vec<u64>,
    pub log_key: Option<String>,
}

#[cfg(test)]
pub(crate) fn typescript_bindings() -> String {
    use ts_rs::{Config, TS};

    let config = Config::default();
    format!(
        "// @generated from Rust by `npm run contracts:generate:installer`.\n\
         // Do not edit this file manually.\n\n\
         export {}\n\n\
         export {}\n\n\
         export {}\n\n\
         export {}\n\n\
         export {}\n",
        InstallerPhase::decl(&config),
        ProgressMode::decl(&config),
        InstallerOutcome::decl(&config),
        InstallerSnapshot::decl(&config),
        InstallerEvent::decl(&config),
    )
}
