use super::mac_supervision_failure::MacSupervisionFailure;
use crate::services::browser::cef_unavailable::CefUnavailableCategory;

#[test]
fn mac_supervision_failures_have_fixed_safe_codes_and_categories() {
    let cases = [
        (
            MacSupervisionFailure::PendingLayout,
            CefUnavailableCategory::Admission,
            "admission-pending-layout",
        ),
        (
            MacSupervisionFailure::PendingMissing,
            CefUnavailableCategory::Admission,
            "admission-pending-missing",
        ),
        (
            MacSupervisionFailure::ActiveSlotOccupied,
            CefUnavailableCategory::Admission,
            "admission-active-slot-occupied",
        ),
        (
            MacSupervisionFailure::MailboxSnapshot,
            CefUnavailableCategory::Admission,
            "admission-mailbox-snapshot",
        ),
        (
            MacSupervisionFailure::GenerationMismatch,
            CefUnavailableCategory::Admission,
            "admission-generation-mismatch",
        ),
        (
            MacSupervisionFailure::Publication,
            CefUnavailableCategory::Admission,
            "admission-publication",
        ),
        (
            MacSupervisionFailure::AuthorityClaim,
            CefUnavailableCategory::Admission,
            "admission-authority-claim",
        ),
        (
            MacSupervisionFailure::Identity,
            CefUnavailableCategory::Admission,
            "admission-identity",
        ),
        (
            MacSupervisionFailure::AuthorityAdmission,
            CefUnavailableCategory::Admission,
            "admission-authority-commit",
        ),
        (
            MacSupervisionFailure::EmergencyInstall,
            CefUnavailableCategory::Admission,
            "admission-emergency-install",
        ),
        (
            MacSupervisionFailure::Liveness,
            CefUnavailableCategory::Reaper,
            "reaper-liveness",
        ),
        (
            MacSupervisionFailure::ClosingClock,
            CefUnavailableCategory::Reaper,
            "reaper-closing-clock",
        ),
        (
            MacSupervisionFailure::PendingCloseSignal,
            CefUnavailableCategory::Reaper,
            "reaper-pending-close-signal",
        ),
        (
            MacSupervisionFailure::AdmittedCloseSignal,
            CefUnavailableCategory::Reaper,
            "reaper-admitted-close-signal",
        ),
        (
            MacSupervisionFailure::EmergencyUnavailable,
            CefUnavailableCategory::Reaper,
            "reaper-unavailable",
        ),
        (
            MacSupervisionFailure::TrackerPanic,
            CefUnavailableCategory::Reaper,
            "reaper-tracker-panic",
        ),
        (
            MacSupervisionFailure::EmergencyReaperPanic,
            CefUnavailableCategory::Reaper,
            "reaper-worker-panic",
        ),
        (
            MacSupervisionFailure::ForcePass,
            CefUnavailableCategory::Reaper,
            "reaper-force-pass",
        ),
        (
            MacSupervisionFailure::TrackerJoinPanic,
            CefUnavailableCategory::Reaper,
            "reaper-tracker-join-panic",
        ),
        (
            MacSupervisionFailure::External(CefUnavailableCategory::Object),
            CefUnavailableCategory::Object,
            "external-object",
        ),
        (
            MacSupervisionFailure::External(CefUnavailableCategory::Permission),
            CefUnavailableCategory::Permission,
            "external-permission",
        ),
        (
            MacSupervisionFailure::External(CefUnavailableCategory::Admission),
            CefUnavailableCategory::Admission,
            "external-admission",
        ),
        (
            MacSupervisionFailure::External(CefUnavailableCategory::Reaper),
            CefUnavailableCategory::Reaper,
            "external-reaper",
        ),
        (
            MacSupervisionFailure::External(CefUnavailableCategory::Sandbox),
            CefUnavailableCategory::Sandbox,
            "external-sandbox",
        ),
    ];

    for (failure, category, code) in cases {
        assert_eq!(failure.category(), category);
        assert_eq!(failure.code(), code);
        assert!(code.len() <= 64);
        assert!(code
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte == b'-'));
    }
}
