pub(super) const MAX_PTY_WRITE_BYTES: usize = 64 * 1024;
pub(super) const MAX_FRAME_BYTES: usize = 64 * 1024;
pub(super) const MAX_IN_FLIGHT_BYTES: usize = 1024 * 1024;
pub(super) const MAX_IN_FLIGHT_FRAMES: usize = 256;
pub(super) const MAX_GROUPS: usize = 128;
pub(super) const MAX_TABS_PER_GROUP: usize = 16;
pub(super) const MAX_TOTAL_TABS: usize = 256;
pub(super) const MAX_GROUP_KEY_BYTES: usize = 128;
pub(super) const MAX_LABEL_BYTES: usize = 512;
