use super::{limits::*, manager::PtyManager, tab_store::*};
use ts_rs::TS;

fn bindings() -> String {
    let config = ts_rs::Config::default();
    format!(
        "// @generated by Rust terminal_contract_tests. Do not edit.\n\nexport {}\nexport {}\nexport const TERMINAL_TABS_VERSION = {TERMINAL_TABS_VERSION} as const;\nexport const MAX_LIVE_TERMINALS = {};\nexport const MAX_GROUPS = {MAX_GROUPS};\nexport const MAX_TABS_PER_GROUP = {MAX_TABS_PER_GROUP};\nexport const MAX_TOTAL_TABS = {MAX_TOTAL_TABS};\nexport const MAX_GROUP_KEY_BYTES = {MAX_GROUP_KEY_BYTES};\nexport const MAX_LABEL_BYTES = {MAX_LABEL_BYTES};\nexport const MAX_WRITE_BYTES = {MAX_PTY_WRITE_BYTES};\nexport const MAX_FRAME_BYTES = {MAX_FRAME_BYTES};\nexport const MAX_IN_FLIGHT_BYTES = {MAX_IN_FLIGHT_BYTES};\n",
        TerminalSavedTab::decl(&config),
        TerminalTabsDocument::decl(&config),
        PtyManager::MAX_PTY_SESSIONS,
    )
}

fn path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../src/types/terminal-contract.generated.ts")
}

#[test]
fn checked_in_terminal_contract_matches_rust() {
    assert_eq!(
        std::fs::read_to_string(path())
            .unwrap()
            .replace("\r\n", "\n"),
        bindings()
    );
}

#[test]
#[ignore = "explicit contract generation"]
fn export_terminal_contract() {
    std::fs::write(path(), bindings()).unwrap();
}
