use super::ForecastProviderSpec;

pub const FORECAST_PROVIDERS: &[ForecastProviderSpec] = &[
    ForecastProviderSpec {
        id: "chronos",
        display_name: "Amazon Chronos",
        category: "forecast",
        base_url: "http://localhost:12000",
        signup_url: "https://huggingface.co/amazon/chronos-2",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "google",
        display_name: "Google TimesFM",
        category: "forecast",
        base_url: "https://huggingface.co/google",
        signup_url: "https://huggingface.co/google/timesfm-2.5-200m-pytorch",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "nixtla",
        display_name: "Nixtla (TimeGPT-2)",
        category: "forecast",
        base_url: "https://api.nixtla.io",
        signup_url: "https://dashboard.nixtla.io",
        requires_api_key: true,
    },
    ForecastProviderSpec {
        id: "datadog",
        display_name: "Datadog Toto 2.0",
        category: "forecast",
        base_url: "https://huggingface.co/Datadog",
        signup_url: "https://huggingface.co/Datadog/Toto-2.0-4m",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "salesforce",
        display_name: "Salesforce MOIRAI 2.0",
        category: "forecast",
        base_url: "https://huggingface.co/Salesforce",
        signup_url: "https://huggingface.co/Salesforce/moirai-2.0-R-small",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "ibm",
        display_name: "IBM FlowState",
        category: "forecast",
        base_url: "https://huggingface.co/ibm-granite",
        signup_url: "https://huggingface.co/ibm-granite/granite-timeseries-flowstate-r1",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "priorlabs",
        display_name: "PriorLabs TabPFN-TS",
        category: "forecast",
        base_url: "https://github.com/PriorLabs/tabpfn-time-series",
        signup_url: "https://github.com/PriorLabs/tabpfn-time-series",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "nxai",
        display_name: "NX-AI TiRex",
        category: "forecast",
        base_url: "https://huggingface.co/NX-AI",
        signup_url: "https://huggingface.co/NX-AI/TiRex",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "foundation-model-research",
        display_name: "Foundation Model Research Kairos",
        category: "forecast",
        base_url: "https://github.com/foundation-model-research/Kairos",
        signup_url: "https://github.com/foundation-model-research/Kairos",
        requires_api_key: false,
    },
    ForecastProviderSpec {
        id: "thuml",
        display_name: "THUML Sundial",
        category: "forecast",
        base_url: "https://github.com/thuml/Sundial",
        signup_url: "https://github.com/thuml/Sundial",
        requires_api_key: false,
    },
];
