// Generated from Beaver's extension contract. Do not edit by hand.

export declare const EXTENSION_API_VERSION: "1";
export declare const EXTENSION_CAPABILITIES: readonly ["tools","events","ui"];
export declare const OPTIONAL_EXTENSION_CAPABILITIES: readonly ["skills","resources","richToolResults"];
export declare const EXTENSION_CONTRIBUTION_TYPES: readonly ["tool","event","ui","skill","resource"];
export declare const EXTENSION_RESULT_BLOCK_TYPES: readonly ["text","file"];
export declare const EXTENSION_RESOURCE_TYPES: readonly ["text","image","file"];
export declare const CORE_TO_HOST_METHODS: readonly ["host.hello","host.reset","host.load","tool.call","event.emit","ui.action"];
export declare const STABLE_HOST_TO_CORE_REQUEST_METHODS: readonly ["app.info","sessions.list","sessions.get","projects.list","mcp.connectors.list","mcp.tool.call","channels.config.get","secrets.provider.get","secrets.mcp.oauth.get","secrets.mcp.env.get","secrets.channel.get"];
export declare const ADVANCED_HOST_TO_CORE_REQUEST_METHODS: readonly [];
export declare const HOST_TO_CORE_NOTIFICATION_METHODS: readonly ["host.load.stage"];
export declare const EXTENSION_EVENTS: readonly ["session.turn.started"];
export declare const EXTENSION_HOST_STATES: readonly ["stopped","starting","running","error"];
export declare const HOST_LOAD_STAGES: readonly ["import","activate","register"];
export declare const EXTENSION_EFFECT_CLASSES: readonly ["read-only","local-write","external-read","external-write","process","secret","unknown"];
export declare const PROTOCOL_ERROR_REASONS: readonly ["core_busy","core_request_timeout","core_transport_failed","core_method_unavailable","core_request_failed","extension_host_busy","extension_host_request_failed","extension_host_fatal"];
export declare const EXTENSION_BACKEND_ERROR_CODES: readonly ["extensions_host_unavailable","extensions_host_busy","extensions_host_timeout","extensions_request_too_large","extensions_request_invalid","extensions_tool_unavailable","extensions_tool_arguments_invalid","extensions_builtin_catalog_invalid","extensions_builtin_catalog_unavailable","extensions_builtin_plugin_invalid","extensions_builtin_entry_missing","extensions_builtin_entry_unavailable","extensions_builtin_entry_invalid","extensions_install_failed","extensions_update_failed","extensions_uninstall_failed","extensions_source_invalid","extensions_package_invalid","extensions_git_download_failed","extensions_git_timeout","extensions_runtime_unavailable","extensions_environment_invalid","extensions_dependency_install_failed","extensions_manifest_invalid","extensions_not_beaver_extension","extensions_api_incompatible","extensions_symlink_unsupported","extensions_already_installed","extensions_limit_reached","extensions_storage_failed","extensions_update_identity_changed","extensions_update_unavailable","extensions_cleanup_failed","extensions_operation_failed","extensions_fingerprint_changed","extensions_fingerprint_failed","extensions_stop_unconfirmed","extensions_registry_entry_ignored","extensions_registry_migration_failed","extensions_recovery_marker_invalid","extensions_load_interrupted","extensions_activation_confirmation_required","extensions_not_found","extensions_host_incompatible","extensions_resource_unavailable","extensions_resource_not_found","extensions_resource_invalid","extensions_resource_too_large","extensions_result_invalid","extensions_result_too_large"];
export declare const HOST_DIAGNOSTIC_CODES: readonly ["module_not_found","syntax_error","activation_failed","registration_failed","import_failed","resource_unavailable","result_invalid"];
export declare const RUNTIME_DIAGNOSTIC_CODES: readonly ["entry_unavailable","load_failed","host_missing_response","advanced_required","ui_manifest_legacy"];
export declare const LIMITS: Readonly<{"fingerprintMaxDepth":16,"fingerprintMaxFileBytes":4194304,"fingerprintMaxFiles":2000,"fingerprintMaxTotalBytes":33554432,"hostRestartWindowSeconds":300,"maxContractCodeChars":96,"maxEventsPerExtension":64,"maxExtensionNameChars":100,"maxExtensionTextChars":2000,"maxExtensions":132,"maxGitLocatorChars":2048,"maxHostProcesses":32,"maxHostRestartsPerWindow":3,"maxIdentifierChars":96,"maxInFlightHandlers":64,"maxInFlightRequests":64,"maxMessageBytes":1048576,"maxMultimodalPreviewsPerContinuation":8,"maxNpmSpecChars":280,"maxParallelEphemeralArtifactBytes":67108864,"maxPathChars":4096,"maxPendingRequests":64,"maxPermissionSummaryChars":512,"maxProjectResults":500,"maxResourceFileBytes":20971520,"maxResourcesPerExtension":64,"maxResultBlocks":16,"maxResultBytes":20971520,"maxResultFiles":8,"maxResultTextBytes":524288,"maxSessionResults":500,"maxSkillsPerExtension":32,"maxTextResourceBytes":262144,"maxTools":256,"maxToolsPerExtension":64,"maxUserExtensions":128,"maxWorkingDirectoryChars":1024,"minLongLivedAppWorkReserve":96}>;
export declare const TIMEOUTS: Readonly<{"coreRequestTimeoutMs":30000,"eventHandlerTimeoutMs":5000,"hostRequestTimeoutMs":60000,"hostStopTimeoutMs":5000,"mcpToolTimeoutMs":25000,"toolCallTimeoutMs":55000,"uiActionTimeoutMs":15000}>;
export type ExtensionCapability = typeof EXTENSION_CAPABILITIES[number];
export type OptionalExtensionCapability = typeof OPTIONAL_EXTENSION_CAPABILITIES[number];
export type ExtensionContributionType = typeof EXTENSION_CONTRIBUTION_TYPES[number];
export type ExtensionResultBlockType = typeof EXTENSION_RESULT_BLOCK_TYPES[number];
export type ExtensionResourceType = typeof EXTENSION_RESOURCE_TYPES[number];
export type CoreToHostMethod = typeof CORE_TO_HOST_METHODS[number];
export type StableHostToCoreRequestMethod = typeof STABLE_HOST_TO_CORE_REQUEST_METHODS[number];
export type AdvancedHostToCoreRequestMethod = typeof ADVANCED_HOST_TO_CORE_REQUEST_METHODS[number];
export type HostToCoreNotificationMethod = typeof HOST_TO_CORE_NOTIFICATION_METHODS[number];
export type ExtensionEvent = typeof EXTENSION_EVENTS[number];
export type ExtensionHostState = typeof EXTENSION_HOST_STATES[number];
export type HostLoadStage = typeof HOST_LOAD_STAGES[number];
export type ExtensionEffectClass = typeof EXTENSION_EFFECT_CLASSES[number];
export type ExtensionProtocolErrorReason = typeof PROTOCOL_ERROR_REASONS[number];
export type ExtensionBackendErrorCode = typeof EXTENSION_BACKEND_ERROR_CODES[number];
export type HostDiagnosticCode = typeof HOST_DIAGNOSTIC_CODES[number];
export type RuntimeDiagnosticCode = typeof RUNTIME_DIAGNOSTIC_CODES[number];
